#!/bin/bash
# Reads config.env and generates main/config/local_config.h
# Run this before build.sh whenever config.env changes.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/config.env"
OUT_FILE="$SCRIPT_DIR/main/config/local_config.h"

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: config.env not found."
    echo "  cp firmware/config.env.example firmware/config.env"
    echo "  # fill in your values, then run setup.sh again"
    exit 1
fi

# Load values
source "$ENV_FILE"

cat > "$OUT_FILE" <<EOF
/* Auto-generated by setup.sh — do not edit manually */
/* Add config.env with your values and re-run setup.sh */

#ifndef LOCAL_CONFIG_H
#define LOCAL_CONFIG_H

#define LOCAL_MQTT_BROKER "${MQTT_BROKER:-}"
#define LOCAL_HA_URL      "${HA_URL:-}"
#define LOCAL_HA_TOKEN    "${HA_TOKEN:-}"

#endif /* LOCAL_CONFIG_H */
EOF

echo "Generated $OUT_FILE"
echo ""
if [ -z "$MQTT_BROKER" ]; then
    echo "  NOTE: MQTT_BROKER is empty — configure via web portal after flashing"
fi
if [ -z "$HA_TOKEN" ]; then
    echo "  NOTE: HA_TOKEN is empty — HA integration will not connect"
fi
echo ""
echo "Ready to build: ./build.sh"
